---
version: "3"
services:
 devopsdb:
   image: charan8215/automation:db
   ports:
     - "3306:3306"
   deploy:
     repilcas: 3
 application:
   image: charan8215/automation:app
   ports:
     - "1111:8080"
   deploy:
     repilcas: 3
   depends_on:
     - "devopsdb"
     
